$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty
# Created by https://github.com/decaycs

# Special
background #0d0f18
foreground #5cfbb8

# Black
color0 #2e384e
color8 #2e384e

# Red
color1 #dd6777
color9 #e26c7c

# Green
color4  #22b455
color12 #22b455

# Yellow
color3  #ecd3a0
color11 #f1d8a5

# Blue
color2  #86aaec
color10 #8baff1

# Magenta
color5  #c296eb
color13 #c79bf0

# Cyan
color6  #93cee9
color14 #98d3ee

# White
color7  #cbced3
color15 #d0d3d8

# Cursor
cursor #cbced3
cursor_text_color #a5b6cf

# Selection highlight
selection_foreground #a5b6cf
selection_background #1c1e27

active_tab_foreground   #22b455
active_tab_background   #0d0f18

inactive_tab_foreground #4A4A4A
inactive_tab_background #0d0f18
